# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://localhost:8000"
  dimensions: ["time", "number", "amount-of-money", "distance","day-of-week"]


policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
